// Populates app/src/main/assets/ from the Eupub renderer + dist. Run before
// building the APK (the outputs are git-ignored, derived artifacts):
//   node prepare-assets.mjs
//
// Produces:
//   assets/reader/{index.html, reader.js, epub.js, viewer-runtime.js,
//                  reader.css, android-bridge.js, purify.js}
//   assets/engine/eupub-engine.mobile.js
//   assets/lexicon.db      (on-disk SQLite lexicon, queried natively by the bridge)
//   assets/sample.epub     (bundled first-launch book)
//   assets/pdf/{viewer.html, viewer.css, pdf-viewer.mobile.js}
//   assets/pdfjs/{pdf.worker.min.mjs, wasm/*, standard_fonts/*}
//   assets/sample.pdf      (+ anything in android/fixtures/*.pdf)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { execFileSync } from 'node:child_process';
import { generateViewerHtml } from '../build/pdf-viewer-html.mjs';

const require = createRequire(import.meta.url);
const HERE = path.dirname(fileURLToPath(import.meta.url)); // Eupub/android
const EUPUB = path.resolve(HERE, '..');
const RENDERER = path.join(EUPUB, 'src', 'renderer');
const DIST = path.join(EUPUB, 'dist');
const EXT = path.resolve(EUPUB, '..', 'euspell_ext');
const ASSETS = path.join(HERE, 'app', 'src', 'main', 'assets');
const READER = path.join(ASSETS, 'reader');
const ENGINE = path.join(ASSETS, 'engine');
const PDF = path.join(ASSETS, 'pdf');
const PDFJS = path.join(ASSETS, 'pdfjs');
const FIXTURES = path.join(HERE, 'fixtures');

fs.mkdirSync(READER, { recursive: true });
fs.mkdirSync(ENGINE, { recursive: true });
fs.mkdirSync(PDF, { recursive: true });

// 1. Reuse the renderer verbatim (the shared, host-agnostic half).
for (const f of ['reader.js', 'epub.js', 'viewer-runtime.js', 'reader.css', 'android-bridge.js', 'purify.js']) {
  fs.copyFileSync(path.join(RENDERER, f), path.join(READER, f));
}

// 2. Android index.html: the desktop page with (a) the CSP retargeted to the
//    single virtual origin, and (b) the bridge shim + host config injected
//    before the renderer scripts (in place of the Electron preload).
let html = fs.readFileSync(path.join(RENDERER, 'index.html'), 'utf8');
// Without a viewport meta an Android WebView lays out at a 980px viewport, so
// clientWidth (which the column geometry is derived from) is far wider than the
// screen and the text overflows the right edge. Pin the layout to device width.
if (!html.includes('<meta charset="utf-8" />')) throw new Error('index.html: charset meta not found');
html = html.replace(
  '<meta charset="utf-8" />',
  '<meta charset="utf-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />'
);
const csp =
  `<meta http-equiv="Content-Security-Policy" content="default-src 'self'; ` +
  `script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; ` +
  `img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self'; frame-src 'self'" />`;
html = html.replace(/<meta http-equiv="Content-Security-Policy"[\s\S]*?\/>/, csp);
const inject =
  `<script>window.__eupubHost={origin:'https://eupub.local',mount:'/book',` +
  `engineUrl:'https://eupub.local/assets/engine/eupub-engine.mobile.js'};</script>\n` +
  `  <script src="android-bridge.js"></script>\n` +
  `  <script src="epub.js"></script>`;
if (!html.includes('<script src="epub.js"></script>')) throw new Error('index.html: epub.js script tag not found');
html = html.replace('<script src="epub.js"></script>', inject);
fs.writeFileSync(path.join(READER, 'index.html'), html);

// 3. The lexicon-excluded engine (host injects each chapter's subset).
const engineSrc = path.join(DIST, 'eupub-engine.mobile.js');
if (!fs.existsSync(engineSrc)) {
  throw new Error('dist/eupub-engine.mobile.js missing — run "npm run build:engine:mobile" in Eupub first.');
}
fs.copyFileSync(engineSrc, path.join(ENGINE, 'eupub-engine.mobile.js'));

// 4. On-disk SQLite lexicon (queried natively by the bridge, per chapter).
execFileSync('node', [path.join(EXT, 'build', 'compile-lexicon-sqlite.mjs'), path.join(ASSETS, 'lexicon.db')], {
  stdio: 'inherit',
});

// 5. A bundled sample book so the first launch shows something.
const { makeEpub } = require(path.join(EUPUB, 'test', 'make-epub.js'));
makeEpub(path.join(ASSETS, 'sample.epub'));

// 6. PDF.js runtime files, copied from euspell_ext's dist (itself generated by
//    that repo's build/copy-pdfjs.js from node_modules/pdfjs-dist).
//
//    These MUST live under /assets/, not /book/: androidx.webkit's
//    AssetsPathHandler knows .mjs -> text/javascript and .wasm ->
//    application/wasm, while MainActivity's own BookPathHandler.guessMime()
//    does not and would serve them as application/octet-stream — which a module
//    worker refuses to execute.
const pdfjsSrc = path.join(EXT, 'dist', 'pdfjs');
if (!fs.existsSync(path.join(pdfjsSrc, 'pdf.worker.min.mjs'))) {
  throw new Error('euspell_ext/dist/pdfjs missing — run "npm run build:pdfjs" in euspell_ext first.');
}
fs.rmSync(PDFJS, { recursive: true, force: true }); // never leave a stale worker behind
fs.cpSync(pdfjsSrc, PDFJS, { recursive: true });

// 7. The mobile PDF viewer bundle (extension APIs aliased out; no baked lexicon —
//    it fetches each page's subset through the bridge, like the engine does).
const pdfBundle = path.join(EXT, 'dist', 'pdf-viewer.mobile.js');
if (!fs.existsSync(pdfBundle)) {
  throw new Error('euspell_ext/dist/pdf-viewer.mobile.js missing — run "npm run build:pdf:mobile" in euspell_ext first.');
}
fs.copyFileSync(pdfBundle, path.join(PDF, 'pdf-viewer.mobile.js'));
fs.copyFileSync(path.join(EXT, 'src', 'pdf', 'viewer.css'), path.join(PDF, 'viewer.css'));

// 8. Android pdf/viewer.html: the extension's viewer page transformed by the
//    shared generator (build/pdf-viewer-html.mjs — header dropped, bridge
//    loaded classic-first, its own CSP), with android-bridge.js as the bridge
//    (it defaults its origin to https://eupub.local, so no host-config script
//    is needed).
fs.writeFileSync(
  path.join(PDF, 'viewer.html'),
  generateViewerHtml(EXT, ['<script src="../reader/android-bridge.js"></script>'])
);

// 9. A sample PDF, plus any real-world PDFs dropped in android/fixtures/.
//    sample.pdf is Helvetica-only, so it exercises standardFontDataUrl but
//    neither embedded fonts nor the wasm decoders — until there's a file picker,
//    fixtures/ is the only way to get a real PDF onto the device.
const { makePdf } = require(path.join(EUPUB, 'test', 'make-pdf.js'));
makePdf(path.join(ASSETS, 'sample.pdf'));

for (const f of fs.existsSync(FIXTURES) ? fs.readdirSync(FIXTURES) : []) {
  if (!/\.pdf$/i.test(f)) continue;
  fs.copyFileSync(path.join(FIXTURES, f), path.join(ASSETS, f));
  console.log('  fixture:', f);
}

console.log('Assets prepared in', ASSETS);
